OCSort: 
  det_thresh: 0.7
  max_age: 120
  min_hits: 3 
  iou_threshold: 0.3
  delta_t: 3
  inertia: 0.2 
  use_byte: True
  low_det_thresh: 0.3
  max_track_num: 60
  create_new_track_det_thresh: 0.65
  create_new_track_det_thresh_stricter: 0.85
  create_new_track_iou_thresh_stricter: 0.3


  # first round priority(with high confident detection): location > appearance 
  first_round_buffer_ratio: 0.2
  first_round_buffer_speed: 5.0
  first_round_match_iou_threshold: 0.3
  first_round_match_v_dir_weight: 0.2
  first_round_match_v_dir_cos_threshold: -1.1  # no requirement at all
  first_round_match_app_threshold: -0.0
  first_round_match_app_weight: 0.5
 
  # second round priority(with low confident detection): location > appearance 
  second_round_buffer_ratio: 0.2
  second_round_buffer_speed: 5.0
  second_round_match_iou_threshold: 0.3
  second_round_match_v_dir_weight: 0.2
  second_round_match_v_dir_cos_threshold: -1.1  # no requirement at all
  second_round_match_app_threshold: -0.3
  second_round_match_app_weight: 0.1

  # third round priority(with high confident detection): appearance > location
  third_round_buffer_ratio: 2.0
  third_round_buffer_speed: 80.0
  third_round_match_iou_threshold: 0.01
  third_round_match_v_dir_weight: 0.2
  third_round_match_v_dir_cos_threshold: 0.5  # 60 degrees
  third_round_match_app_threshold: 0.4
  third_round_match_app_weight: 1.0

  verbose: True

YOLO:
  onnx_path: "my_script/yolov8n_visdrone_add_people_merged_640_640.onnx"
  conf_threshold: 0.25
  nms_threshold: 0.7
  min_w: 10
  min_h: 10

ReID:
  onnx_path: "my_script/fastreid_model_b1_s128.onnx"
  input_size: 128
  feat_dim: 128

EfficientReIDStrategy:
  maximum_num_per_frame: 4  # maximum number for each frame
  iou_threshold: 0.3
  det_thresh: 0.7
  
CMC:
  min_features: 30
  method: "optflow"  # "optflow" or "orb"
  # ui_mask: "./ui_mask.jpg"
  ui_mask: ""
  process_img_shape: [480, 640]  # H, W
  
  
EXP:
  # img_foler: "imgs/screen-20250422-150828_seg_2"
  img_foler: "test_imgs/DJI_20250606154940_0004_V/DJI_20250606154940_0004_V_black_car"
  resize_ratio: 1.0
  use_cmc: True
  delayed_update: False
  use_efficient_strategy: True


